config/routes.rb
EventCasts::Application.routes.draw do |map|
  root :to=>'home#index'
  match '/event/show/:id', :to=>'event#show', :as=>'event_page'  

  match '/user/login/:user', :to=>"user#login", :via=>[:post]    
  match '/messages/persist/:_json', :to=>"messages#persist"  
  match '/messages/:action/:id', :to=>"messages(/:action(/:id))"    
  
  match ':controller(/:action(/:id(.:format)))'
  match '/:id', :to=>"events#show/:id"    
  
  match 'associated_account/start_twitter', :to => 'associated_account#start_twitter', :as => 'start_twitter_session'  
  match 'associated_account/finalize_twitter', :to => 'associated_account#finalize_twitter', :as => 'finalize_twitter_session'
  
  match 'associated_account/add', :to => 'associated_account#add', :as => 'associate_account'
end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :events
  has_many :associated_accounts
  has_many :created_events, :class_name => "Event", :foreign_key => "creator_id"

  validates :ec_username, :uniqueness => true, :presence=>true
  validates :password, :presence=>true  
    
  scope :twitter_account, lambda { |username| joins(:associated_accounts) & AssociatedAccount.twitter & AssociatedAccount.has_username(username) }
    
  def self.get_from_twitter(profile)
    user = User.twitter_account(profile.screen_name).first
    user = create_user_from_twitter(profile) if user.nil?
    user
  end
  
  def self.authenticate(name, password)
    user = self.find_by_ec_username(name)
    if user
      expected_password = encrypted_password(password, user.salt)      
      user = nil if user.hashed_password != expected_password
    end
    user
  end
  
  def password
    @password
  end
  def password=(pwd)
    @password = pwd
    return if pwd.blank?
    create_new_salt
    self.hashed_password = User.encrypted_password(self.password, self.salt)
  end
  
  def display_name    
    ec_username || "@"+twitter_account.username || ""
  end
  
  def twitter_account
    associated_accounts.select { |x| x.associated_account_type_id == 1}.first
  end
  
  def has_account_type(id)
    associated_accounts.each do |account|
      return true if account.associated_account_type_id == id
    end
    return false
  end
  
  def associate_account(screen_name, account_type_id)
    associated_accounts << AssociatedAccount.new(:username => screen_name, :associated_account_type_id=>account_type_id)
  end
  
  def has_all_account_types
    return associated_accounts.count >= AssociatedAccountType.all.count && !ec_username.nil?
  end  
    
  private 
      
  def create_new_salt
    self.salt = self.object_id.to_s + rand.to_s
  end
  
  def self.encrypted_password(password, salt)
    string_to_hash = password + "eventcasts" + salt
    Digest::SHA1.hexdigest(string_to_hash)
  end  
  
  def self.create_user_from_twitter(profile)
    user = User.new(:ec_username=>nil, :password=>nil)
    user.associate_account(profile.screen_name, 1)
    user.save(:validate=>false)
    user
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  include UserHelper
  before_filter :authenticate, :except=>[:login, :register, :verify_login, :start_twitter, :finalize_twitter]
  
  def login
    store_location
    if request.post?
      session[:user] = User.authenticate(params[:user][:ec_username], params[:user][:password])
      if session[:user].nil?        
        authentication_failure()
      else
        redirect_to :controller=>"user", :action=>"home" if !request.xhr?
      end
    end
  end
    
  def register
    store_location
    if !params[:user].nil?
      @user = User.new(params[:user])
      result = @user.save
      if result
        session[:user] = @user  
        if request.xhr?
          render :text => "true", :layout=>false          
        else
          redirect_to :controller=>"user", :action=>"home"
        end
      elsif request.xhr?
        handle_ajax_validation_errors(@user)
      end
    end
  end

  def logout
    session[:user] = nil
    redirect_to "/"
  end
  
  def verify_login
    if session[:user].nil?
      render :partial=>"login", :layout=>false
    else
      render :text => "true", :layout=>false
    end
  end
    
  def home
    render_user_home_layout
  end  
  
  def events
    render_user_home_layout
  end
  
  def accounts
    render_user_home_layout
  end

  def settings
    render_user_home_layout
  end
  
  private
  
  def render_user_home_layout
    displayed_layout = request.xhr? ? false : "user_home"
    render :layout=>displayed_layout        
  end
  
  def authentication_failure()
    flash[:notice] = "Unable to find a user with that username and password."    
    set_ajax_validation_errors("[[\"username\",\"The username or password entered did not match a valid user\"]]") if request.xhr?
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/_event_list.html.erb
<table>
	<thead>
		<th>Event Name</th>
		<th>Description</th>
		<th>Search Terms</th>
		<th>Owner</th>
		<th></th>
	</thead>
	<tbody>
		<tr class='subheading'>
			<td colspan='5'>
				<h4>Events you have created</h4>
			</td>
		</tr>
		<% logged_in_user.created_events.each do |event| %>
			<tr>
				<td><a href='/event/show/<%= event.id %>'><%= event.name %></a></td>
				<td><%= event.description %></td>
				<td><%= event.search_terms.collect{|x| x.term }.join(", ") %></td>
				<td><%= event.creator.display_name %></td>
				<td><a href='javascript:void(0)'>Edit</a> | <a href='javascript:void(0)'>Delete</a></td>
			</tr>
		<% end %>
		<tr class='subheading'>
			<td colspan='5'>
				<h4>Events you are following</h4>
			</td>
		</tr>
		<% logged_in_user.events.each do |event| %>
			<% if !logged_in_user.created_events.include? event %>
				<tr>
					<td><a href='/event/show/<%= event.id %>'><%= event.name %></a></td>
					<td><%= event.description %></td>
					<td><%= event.search_terms.collect{|x| x.term }.join(", ") %></td>
					<td colspan='2'><%= event.creator.display_name %></td>
				</tr>
			<% end %>
		<% end %>
	</tbody>
</table>

app/views/user/_login.html.erb
<%= javascript_include_tag "login_form_popup.js" %>
<%= stylesheet_link_tag 'login_form_popup' %>
<div id="login_form_popup">
	<% form_for :user, :url => {:action=>"login"} do |p| %>
		<%= p.error_messages %>
		<fieldset>
			<div>
				<%= p.label :ec_username, "EventCasts username" %><br />
				<%= p.text_field :ec_username, :size=>30, :maxlength=>140 %>
			</div>
			<div>
				<%= p.label :password, "EventCasts password" %><br />
				<%= p.password_field :password, :size=>30, :maxlength=>140 %>
				<a href='javascript:void(0)' id='forgot_password'>Forgot username or password?</a>
			</div>			
			<div>
				<%= p.submit "Login", :class => "submit" %>
			</div>
				
		</fieldset>
	<% end %>
	<div id='forgot_password_container' class='hidden'>
		<fieldset>
			<legend>Forgot your username or password?</legend>			
			<label id='forgot_password_label' for='forgot_password_email'>Enter your email address</label><br />		
			<input type='text' id='forgot_password_email' name='forgot_password_email' />
			<input type='button' id='forgot_password_submit' value='Retrieve Password' />
		</fieldset>
	</div>
</div>
<div id="create_account_link">
	<a href='javascript:void(0);' id="prompt_create_account">Or, create an account...</a>
</div>
<div id="create_account_popup" class='hidden'>
	<% form_for :user, :url => {:action=>"register"} do |p| %>
		<%= p.error_messages %>
		<fieldset>
			<div>
				<%= p.label :username, "EventCasts username" %><br />
				<%= p.text_field :username, :size=>30, :maxlength=>140 %>
			</div>
			<div>
				<%= p.label :password, "EventCasts password" %><br />
				<%= p.password_field :password, :size=>30, :maxlength=>140 %>
			</div>
			<div>
				<%= p.label :email, "Email Address" %><br />
				<%= p.text_field :email, :size=>30, :maxlength=>255 %>
			</div>
			<div>
				<%= p.submit "Create Account", :class => "submit" %>
			</div>
		</fieldset>
	<% end %>
</div>

<div id='password_reset_content' class='hidden'></div>

<div id='return_to_login_link' class='hidden'>
	<a href='javascript:void(0);' class='return_to_login'>Go back to Login</a>	
</div>	

app/views/user/accounts.html.erb
<h1>Your Associated Accounts</h1>
<% if !logged_in_user.ec_username.nil? %>
	<div id='EC_account_container'>
		<span class='account_title'>EventCasts - <%= logged_in_user.ec_username %></span>
	</div>
<% end %>

<% logged_in_user.associated_accounts.each do |account| %>
	<div id='<%= account.associated_account_type.abbreviation %>_account_container'>
		<span class='account_title'><%= account.associated_account_type.name %> - @<%= account.username %></span>
		<a href='/associated_account/remove/<%= account.id %>' id='remove_<%= account.associated_account_type.abbreviation %>'>(remove)</a>
	</div>
<% end %>
		

<% if !logged_in_user.has_all_account_types %>
	<a href='/associated_account/add' id='associate_account'>Associate a new account</a>
<% end %>

app/views/user/events.html.erb
<h1>Your Events</h1>
<%= render :partial => "event_list" %>

app/views/user/home.erb
<%= javascript_include_tag "index.js" %>
<%= javascript_include_tag "jquery.form.js" %>
<div id='search_container'>
	<% form_for :search, :url => {:action=>"search"}, :html => { :id => "search_form" } do |p| %>
		<%= p.text_field :query, :size=>30, :maxlength=>140, :id=>'search_box', :value=>'Search for conversations' %>
		<a id='search_button' href='#' type='submit' class='submit'></a>
	<% end %>
    <div id='description_text'>
		<span id='examples'>examples: #eventcasts #railsrumble @eventcasts</span>
		<br />
		<p>Needs to be rewritten</p>
	</div>
    <div id='search_results'>
    </div>
</div>
<div id='login_user_section'>
	<div>
		<h4>Welcome @<%= @user.username %>!</h4>
		<br />
		<%= link_to "Add a event", :controller=>"events", :action=>"new" %>
	</div>
	<h4>Manage your events</h4>
	<ul id="user_events">
		<% for event in @user.events %>
	    	<li><a href='/events/<%= event.id %>'><%= event.name %></a></li>
		<% end %>
	</ul>
	<br />
</div>

app/views/user/home.html.erb
The Feed will go here

app/views/user/login.html.erb
<h1>Sign in to EventCasts</h1>

<div id='register_with_service'>
	<h2>Login with your Twitter account</h2>
	<%= link_to image_tag("twitter-signin.png"), start_twitter_session_url, :id=>"twitter_login" %>
</div>

<div id='sign_up'>
	<h2>Login with your EventCasts account</h2>	
	<%= form_for :user, :url => {:action=>"login"} do |p| %>
		<%= p.error_messages %>
		<fieldset>
			<div>
				<%= p.label :ec_username, "Username: " %>
				<%= p.text_field :ec_username, :size=>30, :maxlength=>140 %>
			</div>
			<div>
				<%= p.label :password, "Password: " %>
				<%= p.password_field :password, :size=>30, :maxlength=>140 %>
			</div>
			<div>
				<%= p.submit "Login", :class => "submit" %>
			</div>
		</fieldset>
	<% end %>
</div>

<div class='clearfix'></div>

app/views/user/register.html.erb
<h1>Join EventCasts</h1>
<div id='register_with_service'>
	<h2>Start by signing in with your Twitter account</h2>
	<%= link_to image_tag("twitter-signin.png"), start_twitter_session_url, :id=>"twitter_sign_up" %>
</div>

<div id='sign_up'>
	<h2>Or create an EventCasts Acccount</h2>	
	<%= form_for :user, :url => {:action=>"register"} do |p| %>
		<%= render "shared/error_messages", :target => @user %>
		<fieldset>
			<div>
				<%= p.label :ec_username, "Username: " %>
				<%= p.text_field :ec_username, :size=>30, :maxlength=>140 %>
			</div>
			<div>
				<%= p.label :password, "Password:" %>
				<%= p.password_field :password, :size=>30, :maxlength=>140 %>
			</div>
			<div>
				<%= p.submit "Create User", :class => "submit" %>
			</div>
		</fieldset>
	<% end %>
</div>
<div class='clearfix'></div>

app/views/user/settings.html.erb
Settings go here